services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=movies_bm25
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=movies_vec
      - FEEDBACK_LOG_PATH=/app/data/feedback.jsonl
    volumes:
      - .:/app
      - feedback_data:/app/data
    depends_on:
      - elasticsearch
      - qdrant
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.4.8
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  qdrant_storage:
  feedback_data:
